# Generated by Django 4.2.6 on 2023-10-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reporters", "0001_initial"),
        ("missing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingperson",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person",
                to="reporters.reporter",
            ),
        ),
    ]
