# Generated by Django 4.2.6 on 2023-10-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sighting",
            name="postal_code",
            field=models.CharField(default="10462", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sighting",
            name="state",
            field=models.CharField(default="NY", max_length=20),
            preserve_default=False,
        ),
    ]
