# Generated by Django 4.2.4 on 2023-10-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sighting",
            old_name="reporter",
            new_name="sighting_reporter",
        ),
    ]
