# Generated by Django 4.2.6 on 2023-10-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0002_alter_sighting_postal_code_alter_sighting_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="sighting",
            name="sighting_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
